INSERT INTO courses (course_code, name, credits)
VALUES 
('ES 101', 'Engineering Graphics', 3),
('ES 112', 'Computing', 3),
('ES 113', 'Data Centric Computing', 3),
('ES 114', 'Probability, Statistics and Data Visualization', 3),
('ES 115', 'Design, Innovation and Prototyping', 5),
('ES 116', 'Principles and Applications of Electrical Engineering', 5),
('ES 117', 'The World of Engineering', 2),
('ES 243', 'Biology for Engineers', 4),
('BS 192', 'Undergraduate Science Laboratory', 3),
('CS 203', 'Software Tools & Techniques for AI', 4),
('CS 303', 'Mathematical Foundations for AI', 4),
('CS 328', 'Introduction to Data Science', 4),
('CS 329', 'Foundations of AI: Multiagent Systems', 4),
('CS 201', 'Theory of Computation', 4),
('ES 215', 'Computer Organisation & Architecture', 4),
('ES 335', 'Machine Learning', 4),
('ES 242', 'Data Structures and Algorithms-1', 4),
('ES 204', 'Digital Systems', 4),
('CS 333', 'Ethics of AI', 4),
('CS 613', 'Natural Language Processing', 4),
('ES 615', 'Nature Inspired Computing', 4),
('ES 645', 'Optimization Methods in Machine Learning', 4),
('ES 659', 'Computer Graphics', 4),
('ES 661', 'Probabilistic Machine Learning', 4),
('ES 666', 'Computer Vision', 4),
('ES 667', 'Deep Learning', 4),
('ES 670', 'Matrix Methods for Signal Processing, Data Science, and Machine Learning', 4),
('ES 676', 'Classical Information Theory', 4),
('ME 639', 'Introduction to Robotics', 4),
('CS 301', 'Operating Systems', 4),
('CS 327', 'Compilers', 5),
('CS 432', 'Databases', 4),
('CS 433', 'Computer Networks', 4),
('CS 436', 'History of Computing and its Applications to Domains', 4),
('EE 323', 'Digital Signal Processing', 4),
('ES 214', 'Discrete Mathematics', 4),
('ES 669', 'Advanced Computer Architecture and Systems', 4),
('ES 211', 'Thermodynamics', 3),
('CL 202', 'Chemical Engineering Thermodynamics', 3),
('CL 201', 'Chemical Process Calculations', 3),
('CL 203', 'Process Fluid Mechanics', 3),
('CL 204', 'Heat Transfer', 3),
('CL 205', 'Chemical Reaction Engineering - I', 3),
('CL 313', 'Chemical Reaction Engineering - II', 3),
('CL 314', 'Separation Processes - I', 3),
('CL 315', 'Process Dynamics and Control', 3),
('CL 316', 'Separation Processes - II', 3),
('CL 317', 'Process Synthesis, Design, and Simulation', 4),
('CL 325', 'Transport Phenomena', 3),
('CL 326', 'Integrated Chemical Engineering Lab-I', 3),
('CL 327', 'Integrated Chemical Engineering Lab-II', 3),
('BS 401', 'Nanoscale Science', 4),
('CL 324', 'Introduction to Polymer Science and Engineering', 4),
('CL 353', 'Introduction to Process Safety', 2),
('CL 426', 'Biochemical Engineering', 4),
('CL 427', 'Formulation Science and Engineering', 4),
('ES 604', 'Engineering Optimization', 4),
('ES 617', 'Design of Experiments', 4),
('ES 658', 'Molecular Simulations - Theory and Applications', 4),
('ES 662', 'Flexible Electronics: Materials, Methods and Devices', 4),
('ES 664', 'Scientific Computing using C++', 4),
('CL 601', 'Advance Transport Phenomena', 4),
('CL 602', 'Advanced Thermodynamics', 4),
('CL 604', 'Advanced Reaction Engineering', 4),
('CL 605', 'Colloidal Domain: Where Science Meets Engineering', 4),
('CL 627', 'Particulate Solids: Processing & Surface Engineering', 4),
('CL 628', 'Liquid State Theory', 4),
('CL 629', 'Fundamentals of Aerosol Science', 4),
('CL 630', 'Catalyst Design for Heterogeneous Reactions', 4),
('CE 634', 'Air Pollution Control Engineering', 4),
('ES 221', 'Mechanics of Solids', 4),
('CE 201', 'Earth Materials and Processes', 2),
('CE 303', 'Geospatial Engineering', 2),
('CE 302', 'Structural Analysis', 4),
('ES 212', 'Fluid Mechanics', 4),
('CE 202', 'Sustainability and Environment', 3),
('CE 310', 'Hydrology and Hydraulics', 4),
('CE 312', 'Design of Steel Structures', 4),
('CE 301', 'Soil Mechanics', 5),
('CE 311', 'Design of Reinforced Concrete Structures', 5),
('CE 403', 'Construction Technology & Management', 4),
('CE 313', 'Environmental Science and Engineering', 4),
('CE 314', 'Geotechnical Engineering', 4),
('CE 404', 'Transportation Engineering', 4),
('CE 307', 'Masonry Design', 2),
('CE 603', 'Constitutive Models in Soil Mechanics', 4),
('CE 605', 'Remote Sensing of Land and Water Resources', 4),
('CE 607', 'Advanced Structural Analysis', 4),
('CE 611', 'Advanced Engineering Hydrology', 4),
('CE 613', 'Analysis and Design of Masonry Buildings', 4),
('CE 615', 'Structural Design for Fire', 4),
('CE 622', 'Structural Dynamics', 4),
('CE 624', 'River Engineering', 4),
('CE 625', 'Advanced Hydraulic Engineering', 4),
('CE 626', 'Earthquake Engineering', 4),
('CE 627', 'Slopes and Retaining Structures', 2),
('CE 628', 'Applied Hydraulic Transients', 4),
('CE 629', 'Geosynthetics', 4),
('CE 631', 'Irrigation Engineering and Hydraulic Structures', 4),
('CE 632', 'Advanced Concrete Design', 4),
('CE 635', 'Pavement Materials and Design', 4),
('CE 636', 'Traffic and Roadway Engineering', 4),
('ES 404', 'Networks and Complex Systems', 4),
('CE 638', 'Advanced Concrete Technology', 4),
('EH 610', 'Engineering Seismology and Seismic Hazard', 4),
('ES 607', 'Foundations of Fluid Dynamics', 4),
('ES 621', 'Advanced Solid Mechanics', 4),
('ES 622', 'Finite Element Methods', 4),
('ES 624', 'Non-Linear Elasticity', 4),
('ES 635', 'Water Quality Engineering', 4),
('ES 646', 'Elastodynamics and Vibrations', 4),
('ES 648', 'Nonlinear Dynamics and Vibrations', 4),
('ES 651', 'Computational Inelasticity', 4),
('ES 652', 'Contaminant Transport and Remediation', 4),
('ES 653', 'Nonlinear Continuum Mechanics', 4),
('ES 660', 'Variational Methods in Mechanics', 4),
('ES 671', 'Mechanics of Composite Materials', 4),
('ME 605', 'Computational Fluid Dynamics', 4),
('ME 628', 'Advanced Fluid Mechanics', 4),
('ME 640', 'Fracture Mechanics', 4),
('CS 202', 'Software Tools and Techniques for CSE', 4),
('CS 331', 'Computer Networks', 4),
('ES 627', 'Linear Algebra and Computation', 4),
('ES 637', 'Mathematical Foundations for Computer Vision and Graphics', 4),
('ES 301', 'Data Structures & Algorithms II', 4),
('CS 614', 'Advanced Algorithms', 4),
('CS 617', 'Computational Complexity Theory', 4),
('CS 431', 'Computer and Network Security', 4),
('CS 434', 'Software Engineering and Testing', 4),
('CS 435', 'Human–Computer Interaction', 4),
('CS 615', 'Advanced Networks', 4),
('CS 616', 'Parallel and Distributed Systems', 5),
('ES 668', '5G and Beyond', 4),
('ES 244', 'Signals, Systems & Random Processes', 4),
('EE 226', 'Semiconductor Devices', 4),
('EE 331', 'Electrical Machines', 4),
('EE 332', 'Power Systems', 4),
('EE 333', 'Power Electronics', 4),
('EE 312', 'Engineering Electromagnetics', 4),
('EE 313', 'Communication Systems', 3),
('EE 322', 'Analog & Mixed Signal Circuits', 4),
('ES 245', 'Control Systems', 4),
('ES 333', 'Microprocessors and Embedded Systems', 4),
('ES 412', 'Optical Fiber Communication', 4),
('ES 414', 'Introduction to Photonics', 4),
('ES 416', 'Space Science and Satellite Technology', 4),
('ES 408', 'Mechatronics', 4),
('ES 612', 'Artificial Intelligence', 4),
('ES 613', 'Modern Control Theory', 4),
('ES 616', 'Digital Control Systems', 4),
('ES 625', 'Optical Communications', 4),
('ES 626', 'Microfabrication and Semiconductor Processes', 4),
('ES 641', 'Electronic Instrumentation', 4),
('ES 642', 'Control of Nonlinear Dynamical Systems', 4),
('ES 655', 'Medical Imaging Systems', 4),
('ES 656', 'Human-Robot Interaction', 4),
('ES 657', 'Biomedical Ultrasound', 4),
('ES 663', 'Smart Renewable Energy Systems', 4),
('ES 665', 'Advanced Transportation Electrification Technology', 4),
('ES 675', 'Photonics – Principles and Applications', 4),
('PH 643', 'Quantum Computing and Information', 4),
('EE 225', 'Unveiling the Semiconductor World', 2),
('EE 227', 'CMOS Circuit Design', 4),
('ES 339', 'IC Fabrication Lab', 2),
('EE 651', 'CMOS Analog IC Design', 6),
('EE 660', 'Power Management IC Design', 4),
('ES 246', 'Vacuum Technology Laboratory', 2),
('ES 672', 'Semiconductor Packaging', 4),
('MSE 202', 'Materials Thermodynamics', 4),
('MSE 204', 'Transport Phenomena in Materials Engineering', 4),
('MSE 201', 'Microstructural Engineering', 5),
('MSE 206', 'Physics of Materials', 4),
('MSE 203', 'Integrated Computational Materials Engineering', 4),
('MSE 205', 'Mechanical Behaviour of Materials', 4),
('MSE 313', 'Polymers, Ceramics and Composites', 4),
('MSE 315', 'Integrated Computational Materials Engineering', 4),
('MSE 307', 'Materials Processing', 4),
('ES 415', 'Nature-inspired Materials Design', 4),
('ES 623', 'Biomolecular Materials Science', 4),
('MSE 355', 'Surface Engineering', 4),
('MSE 401', 'Introduction to Polymer Physics and Processing', 4),
('MSE 402', 'Computational Process Design', 4),
('MSE 403', 'Science and Technology of Welding and Joining', 4),
('MSE 404', 'Diffraction Methods for Structure and Stress Analysis', 4),
('MSE 604', 'Deformation Behaviour of Materials', 4),
('MSE 603', 'Thin Film Processing and Characterization', 4),
('MSE 605', 'Biomaterials for Tissue Regeneration', 4),
('MSE 621', 'Process Plant Design – How to Set Up a Process Industry', 4),
('MSE 622', 'Process Plant Design – How to Set Up a Process Industry', 4),
('MSE 210', 'Microstructural Engineering', 4),
('MSE 209', 'Material Thermodynamics and Kinetics', 4),
('MSE 631', 'Thermodynamics of Materials', 4),
('MSE 625', 'Thermodynamics of Thin Film Growth', 4),
('MSE 311', 'Transport Phenomena in Materials Engineering', 4),
('MSE 303', 'Mechanical Behaviour of Materials', 4),
('MSE 310', 'Physics of Materials', 4),
('MSE 207', 'Structure of Materials', 4),
('MSE 629', 'Structure and Defects of Materials', 4),
('MSE 211', 'Material Characterization Techniques', 3),
('MSE 352', 'Material Characterization Techniques', 4),
('MSE 632', 'Characterization of Materials', 4),
('MSE 633', 'Transmission Electron Microscopy', 5),
('MSE 302', 'Corrosion and Degradation of Materials', 4),
('MSE 316', 'Corrosion and Degradation of Materials', 4),
('MSE 304', 'Principles of Metal Extraction and Refining', 4),
('MSE 305', 'Advanced Materials', 4),
('MSE 628', 'Advanced Engineering Materials', 4),
('MSE 306', 'Design, Selection and Processing of Engineering Alloys', 2),
('MSE 317', 'Materials Processing (lab variant)', 4),
('MSE 318', 'Introduction to Quantum Materials and Devices', 3),
('MSE 354', 'Heat Treatment of Alloys', 2),
('MSE 312', 'Materials and Environment', 2),
('MSE 314', 'Materials Selection and Design', 3),
('MSE 624', 'Thermo-mechanical Processing', 4),
('MSE 626', 'Light Metal Alloys for Automotive Industry', 4),
('MSE 627', 'Interfaces in Materials', 4),
('MSE 630', 'Kinetics of Materials', 4),
('MSE 634', 'Semiconductor Materials and Fabrication Process', 4),
('MSE 635', 'Advanced Alloy Design and Processing', 4),
('MSE 636','AI for Materials Engineering', 4),
('ME 206', 'Statics & Dynamics', 4),
('ME 207', 'Fluid Dynamics', 5),
('ME 209', 'Principles of Manufacturing Processes', 3),
('ME 208', 'Vibrations', 2),
('ME 334', 'Heat and Mass Transfer', 4),
('ME 362', 'Introduction to Manufacturing Systems & Metrology', 3),
('ME 333', 'Mechanics of Materials', 3),
('ME 322', 'Synthesis and Analysis of Mechanisms', 3),
('ME 337', 'Mechanical Systems Design', 3),
('ES 337', 'Energy Systems', 3),
('ES 631', 'Advanced Heat Transfer', 3),
('ES 632', 'Energy Systems', 4),
('PH 201', 'Introduction to Electrodynamics', 4),
('PH 202', 'Introduction to Quantum Physics', 4),
('PH 203', 'Solid State Physics', 4),
('PH 404', 'Molecular and Crystal Physics', 4),
('PH 503', 'Quantum Mechanics I', 4),
('PH 505', 'Classical Electrodynamics', 4),
('PH 507', 'Statistical Mechanics', 4),
('PH 508', 'Classical Mechanics', 4),
('PH 509', 'Computational Physics', 4),
('PH 510', 'Condensed Matter Physics', 4),
('CH 203', 'Fundamentals and Applications of Spectroscopy', 4),
('CH 204', 'Organic Chemistry in Everyday Life', 4),
('CH 302', 'Electrochemical Science and Engineering', 4),
('CH 401', 'Food Chemistry', 4),
('CH 511', 'Quantum Chemistry', 4),
('CG 503', 'Fundamentals of Cognitive Psychology', 4),
('CG 505', 'Fundamental Neuroscience', 4),
('EH 303', 'Introduction to Earth Sciences', 4),
('EH 304', 'Drone Data Acquisition Processing and Interpretation', 2),
('EH 601', 'Earth Surface Processes', 4),
('EH 602', 'River Morphology and Ecology', 4),
('EH 605', 'Modeling of Earth System and Sustainability', 4),
('EH 608', 'Biodiversity Conservation and Sustainable Development', 4),
('EH 611', 'Near Surface Geophysics', 4),
('EH 612', 'Ocean and Global Change', 4),
('EH 619', 'Geobiology', 4),
('EH 621', 'Climate of the Past', 4),
('ES 118', 'Materials for the Future', 3),
('HS 191', 'Introduction to Writing I', 2),
('HS 192', 'Introduction to Writing II', 2),
('HS 151', 'Economics', 4),
('GE 101', 'General Education I', 2),
('GE 201', 'General Education II', 2),
('MA 204', 'Introduction to Partial Differential Equations', 2),
('MA 205', 'Calculus of Several Variables', 2),
('MA 206', 'Introduction to Complex Analysis', 2);

INSERT INTO courses (name, credits)
VALUES
('Reinforcement Learning', 4),
('Game Theory', 4),
('Knowledge Representation and Reasoning', 4),
('Speech Technology', 4),
('AI for Sustainability', 4),
('AI for Earth Sciences', 4),
('AI for Biological Engineering', 4),
('Software Engineering', 4),
('Semiconductor Material & Device Characterization', 4),
('IC Fabrication & Manufacturing', 4),
('Thin Film Science & Vacuum Technology', 4),
('Semiconductor Package Assembly & Manufacturing', 4),
('Materials & Environment', 2);

INSERT INTO courses (name)
VALUES
('Advanced Semiconductor Manufacturing'),
('Compound Semiconductor Devices & Circuits'),
('Design for Test'),
('Display Technology and Manufacturing'),
('Fundamentals of MEMS/NEMS'),
('Manufacturing Process Control'),
('Memory Devices, Circuits & Systems'),
('Nanoscale Devices'),
('Physics and Manufacturing of Solar Cells'),
('Power Semiconductor Devices'),
('RF IC Design'),
('VLSI Physical Design: Netlist to GDSII'),
('Irrigation Engineering and Hydraulic Structures'),
('Data Sciences for Earth Systems'),
('Advance Design of (Steel/Concrete)'),
('Advance Courses in Transportation Engineering');

INSERT INTO courses (course_code, name)
VALUES
('CS 332', 'Principles of Programming Languages');